image: gitpod/workspace-full
checkoutLocation: gitpod-k3s
tasks: 
  - name: gclient
    command: |
      pushd ..
      git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
      popd
      export PATH=$PATH:`realpath ../depot_tools`

      mkdir ../webrtc
      pushd ../webrtc
      fetch --no-history webrtc 
      popd

  - name: build
    command: |
      export PATH=$PATH:`realpath ../depot_tools`
      cmake .
      make

ports:
  - port: 8000
    onOpen: open-browser
vscode:
  extensions:
    - kubernetes